// This file is auto-generated by Supabase CLI.
// Run: supabase gen types typescript --project-id <ref> > src/lib/supabase/database.types.ts
// Do not edit manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      organisations: {
        Row: {
          id: string
          name: string
          created_by: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          created_by: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          created_by?: string
          created_at?: string
        }
      }
      org_members: {
        Row: {
          org_id: string
          user_id: string
          role: 'admin' | 'associate' | 'viewer'
          joined_at: string
        }
        Insert: {
          org_id: string
          user_id: string
          role?: 'admin' | 'associate' | 'viewer'
          joined_at?: string
        }
        Update: {
          org_id?: string
          user_id?: string
          role?: 'admin' | 'associate' | 'viewer'
          joined_at?: string
        }
      }
      org_invites: {
        Row: {
          id: string
          org_id: string
          invited_email: string
          invited_by: string
          token: string
          status: 'pending' | 'accepted' | 'rejected' | 'expired'
          expires_at: string
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          invited_email: string
          invited_by: string
          token?: string
          status?: 'pending' | 'accepted' | 'rejected' | 'expired'
          expires_at?: string
          created_at?: string
        }
        Update: {
          status?: 'pending' | 'accepted' | 'rejected' | 'expired'
        }
      }
      clients: {
        Row: {
          id: string
          org_id: string
          name: string
          gstin: string | null
          company_name: string | null
          contact_info: Json
          deleted_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          name: string
          gstin?: string | null
          company_name?: string | null
          contact_info?: Json
          deleted_at?: string | null
          created_at?: string
        }
        Update: {
          name?: string
          gstin?: string | null
          company_name?: string | null
          contact_info?: Json
          deleted_at?: string | null
        }
      }
      matters: {
        Row: {
          id: string
          org_id: string
          client_id: string
          title: string
          financial_year: string | null
          description: string | null
          status: 'active' | 'stayed' | 'disposed' | 'appeal_pending' | 'tribunal' | 'high_court' | 'supreme_court' | 'closed'
          deleted_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          client_id: string
          title: string
          financial_year?: string | null
          description?: string | null
          status?: 'active' | 'stayed' | 'disposed' | 'appeal_pending' | 'tribunal' | 'high_court' | 'supreme_court' | 'closed'
          deleted_at?: string | null
          created_at?: string
        }
        Update: {
          title?: string
          financial_year?: string | null
          description?: string | null
          status?: 'active' | 'stayed' | 'disposed' | 'appeal_pending' | 'tribunal' | 'high_court' | 'supreme_court' | 'closed'
          deleted_at?: string | null
        }
      }
      documents: {
        Row: {
          id: string
          matter_id: string
          org_id: string
          doc_type: string | null
          reference_number: string | null
          doc_date: string | null
          direction: 'incoming' | 'outgoing' | null
          issued_by: string | null
          financial_year: string | null
          status: 'uploaded' | 'processing' | 'analyzed' | 'placed' | 'pending_placement' | 'failed' | 'needs_review'
          review_status: 'unreviewed' | 'reviewed'
          reviewed_by: string | null
          reviewed_at: string | null
          summary: string | null
          raw_metadata: Json
          ai_prompt_version: string | null
          embedding: number[] | null
          storage_path: string
          file_hash_sha256: string | null
          content_hash: string | null
          created_by: string | null
          created_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          matter_id: string
          org_id: string
          doc_type?: string | null
          reference_number?: string | null
          doc_date?: string | null
          direction?: 'incoming' | 'outgoing' | null
          issued_by?: string | null
          financial_year?: string | null
          status?: 'uploaded' | 'processing' | 'analyzed' | 'placed' | 'pending_placement' | 'failed' | 'needs_review'
          review_status?: 'unreviewed' | 'reviewed'
          reviewed_by?: string | null
          reviewed_at?: string | null
          summary?: string | null
          raw_metadata?: Json
          ai_prompt_version?: string | null
          embedding?: number[] | null
          storage_path: string
          file_hash_sha256?: string | null
          content_hash?: string | null
          created_by?: string | null
          created_at?: string
          deleted_at?: string | null
        }
        Update: {
          doc_type?: string | null
          reference_number?: string | null
          doc_date?: string | null
          direction?: 'incoming' | 'outgoing' | null
          issued_by?: string | null
          financial_year?: string | null
          status?: 'uploaded' | 'processing' | 'analyzed' | 'placed' | 'pending_placement' | 'failed' | 'needs_review'
          review_status?: 'unreviewed' | 'reviewed'
          reviewed_by?: string | null
          reviewed_at?: string | null
          summary?: string | null
          raw_metadata?: Json
          ai_prompt_version?: string | null
          embedding?: number[] | null
          file_hash_sha256?: string | null
          content_hash?: string | null
          deleted_at?: string | null
        }
      }
      document_links: {
        Row: {
          id: string
          from_doc_id: string
          to_doc_id: string
          link_type: 'responds_to' | 'arises_from' | 'challenges' | 'summarizes'
          confidence: number | null
          status: 'confirmed' | 'pending' | 'rejected'
          pending_ref_number: string | null
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          from_doc_id: string
          to_doc_id: string
          link_type: 'responds_to' | 'arises_from' | 'challenges' | 'summarizes'
          confidence?: number | null
          status?: 'confirmed' | 'pending' | 'rejected'
          pending_ref_number?: string | null
          created_by?: string | null
          created_at?: string
        }
        Update: {
          status?: 'confirmed' | 'pending' | 'rejected'
          confidence?: number | null
          pending_ref_number?: string | null
        }
      }
      supporting_documents: {
        Row: {
          id: string
          matter_id: string
          org_id: string
          category: 'invoices' | 'bank_statements' | 'contracts' | 'correspondence' | 'others'
          title: string
          doc_date: string | null
          amount: number | null
          parties: string[] | null
          description: string | null
          raw_metadata: Json
          storage_path: string
          was_promoted: boolean
          created_by: string | null
          created_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          matter_id: string
          org_id: string
          category?: 'invoices' | 'bank_statements' | 'contracts' | 'correspondence' | 'others'
          title: string
          doc_date?: string | null
          amount?: number | null
          parties?: string[] | null
          description?: string | null
          raw_metadata?: Json
          storage_path: string
          was_promoted?: boolean
          created_by?: string | null
          created_at?: string
          deleted_at?: string | null
        }
        Update: {
          category?: 'invoices' | 'bank_statements' | 'contracts' | 'correspondence' | 'others'
          title?: string
          doc_date?: string | null
          amount?: number | null
          description?: string | null
          deleted_at?: string | null
          was_promoted?: boolean
        }
      }
      deadlines: {
        Row: {
          id: string
          matter_id: string
          document_id: string | null
          type: 'appeal_window' | 'pre_deposit' | 'hearing_date' | 'reply_deadline' | 'stay_application' | 'other'
          due_date: string
          description: string | null
          reminder_sent_30d: boolean
          reminder_sent_7d: boolean
          is_resolved: boolean
          resolved_by: string | null
          resolved_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          matter_id: string
          document_id?: string | null
          type: 'appeal_window' | 'pre_deposit' | 'hearing_date' | 'reply_deadline' | 'stay_application' | 'other'
          due_date: string
          description?: string | null
          reminder_sent_30d?: boolean
          reminder_sent_7d?: boolean
          is_resolved?: boolean
          resolved_by?: string | null
          resolved_at?: string | null
          created_at?: string
        }
        Update: {
          due_date?: string
          description?: string | null
          is_resolved?: boolean
          resolved_by?: string | null
          resolved_at?: string | null
          reminder_sent_30d?: boolean
          reminder_sent_7d?: boolean
        }
      }
      case_notes: {
        Row: {
          id: string
          matter_id: string
          document_id: string | null
          org_id: string
          author_id: string
          content: string
          template_type: 'hearing_note' | 'client_instruction' | 'research_note' | 'general'
          is_action_item: boolean
          action_item_assignee: string | null
          action_item_due_date: string | null
          action_item_resolved: boolean
          is_pinned: boolean
          parent_note_id: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          matter_id: string
          document_id?: string | null
          org_id: string
          author_id: string
          content: string
          template_type?: 'hearing_note' | 'client_instruction' | 'research_note' | 'general'
          is_action_item?: boolean
          action_item_assignee?: string | null
          action_item_due_date?: string | null
          action_item_resolved?: boolean
          is_pinned?: boolean
          parent_note_id?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          content?: string
          template_type?: 'hearing_note' | 'client_instruction' | 'research_note' | 'general'
          is_action_item?: boolean
          action_item_assignee?: string | null
          action_item_due_date?: string | null
          action_item_resolved?: boolean
          is_pinned?: boolean
          deleted_at?: string | null
          updated_at?: string
        }
      }
      activity_logs: {
        Row: {
          id: string
          org_id: string
          user_id: string | null
          action: string
          entity_type: string
          entity_id: string | null
          description: string | null
          metadata: Json
          is_reversible: boolean
          reversed_by: string | null
          reversed_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          user_id?: string | null
          action: string
          entity_type: string
          entity_id?: string | null
          description?: string | null
          metadata?: Json
          is_reversible?: boolean
          reversed_by?: string | null
          reversed_at?: string | null
          created_at?: string
        }
        Update: {
          reversed_by?: string | null
          reversed_at?: string | null
        }
      }
      notifications: {
        Row: {
          id: string
          org_id: string
          user_id: string
          type: string
          title: string
          body: string | null
          entity_type: string | null
          entity_id: string | null
          is_read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          user_id: string
          type: string
          title: string
          body?: string | null
          entity_type?: string | null
          entity_id?: string | null
          is_read?: boolean
          created_at?: string
        }
        Update: {
          is_read?: boolean
        }
      }
      wiki_sections: {
        Row: {
          id: string
          matter_id: string
          section_key: string
          title: string
          content: Json
          is_user_edited: boolean
          last_ai_content: Json | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          id?: string
          matter_id: string
          section_key: string
          title: string
          content?: Json
          is_user_edited?: boolean
          last_ai_content?: Json | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          title?: string
          content?: Json
          is_user_edited?: boolean
          last_ai_content?: Json | null
          updated_at?: string
          updated_by?: string | null
        }
      }
      staged_documents: {
        Row: {
          id: string
          org_id: string
          uploaded_by: string
          storage_path: string
          status: 'pending_assignment' | 'analyzing' | 'ready_to_assign' | 'assigned'
          suggested_matter_ids: Json
          raw_metadata: Json
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          uploaded_by: string
          storage_path: string
          status?: 'pending_assignment' | 'analyzing' | 'ready_to_assign' | 'assigned'
          suggested_matter_ids?: Json
          raw_metadata?: Json
          created_at?: string
        }
        Update: {
          status?: 'pending_assignment' | 'analyzing' | 'ready_to_assign' | 'assigned'
          suggested_matter_ids?: Json
          raw_metadata?: Json
        }
      }
      user_notification_prefs: {
        Row: {
          user_id: string
          org_id: string
          email_on_mention: boolean
          email_on_deadline: boolean
          email_on_invite: boolean
          email_on_new_doc: boolean
          email_on_failure: boolean
        }
        Insert: {
          user_id: string
          org_id: string
          email_on_mention?: boolean
          email_on_deadline?: boolean
          email_on_invite?: boolean
          email_on_new_doc?: boolean
          email_on_failure?: boolean
        }
        Update: {
          email_on_mention?: boolean
          email_on_deadline?: boolean
          email_on_invite?: boolean
          email_on_new_doc?: boolean
          email_on_failure?: boolean
        }
      }
      supporting_doc_links: {
        Row: {
          id: string
          supporting_doc_id: string
          document_id: string
          note: string | null
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          supporting_doc_id: string
          document_id: string
          note?: string | null
          created_by?: string | null
          created_at?: string
        }
        Update: {
          note?: string | null
        }
      }
      wiki_section_versions: {
        Row: {
          id: string
          wiki_section_id: string
          content: Json
          generated_by: string
          created_at: string
        }
        Insert: {
          id?: string
          wiki_section_id: string
          content: Json
          generated_by: string
          created_at?: string
        }
        Update: never
      }
    }
    Views: Record<string, never>
    Functions: {
      is_org_member: {
        Args: { check_org_id: string }
        Returns: boolean
      }
      is_org_admin: {
        Args: { check_org_id: string }
        Returns: boolean
      }
      my_org_ids: {
        Args: Record<string, never>
        Returns: string[]
      }
    }
    Enums: {
      org_member_role: 'admin' | 'associate' | 'viewer'
      invite_status: 'pending' | 'accepted' | 'rejected' | 'expired'
      doc_direction: 'incoming' | 'outgoing'
      doc_status: 'uploaded' | 'processing' | 'analyzed' | 'placed' | 'pending_placement' | 'failed' | 'needs_review'
      doc_review_status: 'unreviewed' | 'reviewed'
      link_type: 'responds_to' | 'arises_from' | 'challenges' | 'summarizes'
      link_status: 'confirmed' | 'pending' | 'rejected'
      supporting_doc_category: 'invoices' | 'bank_statements' | 'contracts' | 'correspondence' | 'others'
      staged_status: 'pending_assignment' | 'analyzing' | 'ready_to_assign' | 'assigned'
      deadline_type: 'appeal_window' | 'pre_deposit' | 'hearing_date' | 'reply_deadline' | 'stay_application' | 'other'
      note_template_type: 'hearing_note' | 'client_instruction' | 'research_note' | 'general'
      matter_status: 'active' | 'stayed' | 'disposed' | 'appeal_pending' | 'tribunal' | 'high_court' | 'supreme_court' | 'closed'
      entity_type: 'document' | 'matter' | 'client' | 'case_note' | 'document_link' | 'deadline' | 'wiki_section' | 'organisation' | 'user' | 'staged_document' | 'supporting_document'
      notification_type: 'org_invite' | 'mention' | 'deadline_approaching' | 'document_ready' | 'chain_suggestion' | 'processing_failed' | 'staged_doc_ready' | 'wiki_ai_suggestion'
    }
  }
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']

export type Enums<T extends keyof Database['public']['Enums']> =
  Database['public']['Enums'][T]
