/** Offline fixture/model for the approved Search rebuild. It makes no application, DB, or provider calls. */

type Tenant = 'org-alpha' | 'org-beta'
type Category = 'exact' | 'legal' | 'synonym' | 'numeric' | 'date-fy' | 'compound' | 'availability' | 'multilingual' | 'negative' | 'isolation'
type Kind = 'client' | 'matter' | 'document' | 'passage' | 'financial'
type Availability = 'source_indexed' | 'metadata_only' | 'source_unreadable'
type AmountOperator = 'eq' | 'gt' | 'gte' | 'lt' | 'lte' | 'between'
type Constraints = { kind?: Kind; legalAlias?: string; concept?: string; conceptsAll?: string[]; financialYear?: string; date?: { operator: 'on' | 'before' | 'after' | 'between'; value: string; upperValue?: string }; amount?: { operator: AmountOperator; valuePaise: string; upperValuePaise?: string }; availability?: Availability }
type Source = { id: string; tenant: Tenant; kind: Kind; title: string; legacyFields: string[]; active: boolean; deleted: boolean; legalAliases?: string[]; concepts?: string[]; documentDate?: string; financialYear?: string; amountPaise?: string; contentAvailability?: Availability; citation?: { documentId: string; page: number; anchor: string }; sourceLink: string; semanticQueries?: string[] }
type EvaluationCase = { id: string; category: Category; tenant: Tenant; query: string; expected: { resultIds: string[]; absentResultIds?: string[]; nonDisclosure?: boolean }; constraints?: Constraints; notes?: string }
type Corpus = { version: string; results: Source[]; cases: EvaluationCase[] }
type LegacyRun = { resultIds: string[]; usageLogged: boolean; semanticFallback: boolean }

export const CORPUS_VERSION = 'search-evaluation-v1'
const row = (value: Source) => value
const results: Source[] = [
  row({ id: 'client-alpha-amber', tenant: 'org-alpha', kind: 'client', title: 'Amber Synthetic', legacyFields: ['Amber Synthetic', 'client amber', 'GSTIN-SYN-ALPHA-01'], active: true, deleted: false, sourceLink: '/synthetic/clients/alpha-amber' }),
  row({ id: 'matter-alpha-appeal', tenant: 'org-alpha', kind: 'matter', title: 'Alpha Appeal', legacyFields: ['Alpha Appeal', 'Appeal Amber', 'MAT-ALPHA-AP-01'], active: true, deleted: false, legalAliases: ['section-6'], concepts: ['appeal'], financialYear: '2021-22', sourceLink: '/synthetic/matters/alpha-appeal' }),
  row({ id: 'matter-alpha-limitation', tenant: 'org-alpha', kind: 'matter', title: 'Alpha Limitation', legacyFields: ['Alpha Limitation', 'LIM-ALPHA-21'], active: true, deleted: false, concepts: ['limitation'], financialYear: '2021-22', sourceLink: '/synthetic/matters/alpha-limitation' }),
  row({ id: 'doc-alpha-notice-1400', tenant: 'org-alpha', kind: 'document', title: 'Synthetic Notice 1400', legacyFields: ['Synthetic Notice 1400', 'notice-1400.pdf', 'REF-ALPHA-1400'], active: true, deleted: false, concepts: ['appeal'], documentDate: '2021-07-15', financialYear: '2021-22', contentAvailability: 'source_indexed', citation: { documentId: 'doc-alpha-notice-1400', page: 1, anchor: 'synthetic-notice' }, sourceLink: '/synthetic/documents/alpha-notice-1400' }),
  row({ id: 'doc-alpha-order-natural-justice', tenant: 'org-alpha', kind: 'document', title: 'Synthetic Fair Hearing Order', legacyFields: ['Synthetic Fair Hearing Order', 'REF-ALPHA-NJ'], active: true, deleted: false, concepts: ['natural-justice', 'appeal'], documentDate: '2021-07-15', financialYear: '2021-22', contentAvailability: 'source_indexed', citation: { documentId: 'doc-alpha-order-natural-justice', page: 2, anchor: 'synthetic-hearing' }, sourceLink: '/synthetic/documents/alpha-natural-justice', semanticQueries: ['natural justice', 'fair hearing', 'audi alteram partem', 'opportunity to be heard', 'procedural fairness', 'hearing denied', 'due process', 'right to respond', 'fair procedure', 'hearing opportunity', 'justice natural', 'no hearing'] }),
  row({ id: 'doc-alpha-scan-ocr', tenant: 'org-alpha', kind: 'document', title: 'Synthetic Scanned Order', legacyFields: ['Synthetic Scanned Order', 'OCR-SCAN-ALPHA'], active: true, deleted: false, legalAliases: ['section-6'], concepts: ['appeal'], financialYear: '2021-22', contentAvailability: 'source_unreadable', sourceLink: '/synthetic/documents/alpha-scan' }),
  row({ id: 'doc-alpha-import-register', tenant: 'org-alpha', kind: 'document', title: 'Synthetic Imported Register', legacyFields: ['Synthetic Imported Register', 'REGISTER-ALPHA-21'], active: true, deleted: false, financialYear: '2021-22', contentAvailability: 'metadata_only', sourceLink: '/synthetic/documents/alpha-register' }),
  row({ id: 'passage-alpha-section-6', tenant: 'org-alpha', kind: 'passage', title: 'Synthetic Section 6 Passage', legacyFields: ['S6-ALPHA'], active: true, deleted: false, legalAliases: ['section-6'], concepts: ['appeal'], documentDate: '2021-07-15', financialYear: '2021-22', contentAvailability: 'source_indexed', citation: { documentId: 'doc-alpha-notice-1400', page: 1, anchor: 'section-6' }, sourceLink: '/synthetic/documents/alpha-notice-1400#section-6' }),
  row({ id: 'passage-alpha-fy-2021', tenant: 'org-alpha', kind: 'passage', title: 'Synthetic FY Passage', legacyFields: ['FY21-ALPHA'], active: true, deleted: false, concepts: ['limitation'], documentDate: '2021-07-15', financialYear: '2021-22', contentAvailability: 'source_indexed', citation: { documentId: 'doc-alpha-notice-1400', page: 1, anchor: 'fy-2021' }, sourceLink: '/synthetic/documents/alpha-notice-1400#fy-2021' }),
  row({ id: 'financial-alpha-demand-1400-01', tenant: 'org-alpha', kind: 'financial', title: 'Synthetic Demand Above Boundary', legacyFields: ['Demand-1400-01'], active: true, deleted: false, concepts: ['appeal'], financialYear: '2021-22', amountPaise: '140000001', sourceLink: '/synthetic/financials/alpha-1400-01' }),
  row({ id: 'financial-alpha-demand-1400-00', tenant: 'org-alpha', kind: 'financial', title: 'Synthetic Demand Boundary', legacyFields: ['Demand-1400-00'], active: true, deleted: false, financialYear: '2021-22', amountPaise: '140000000', sourceLink: '/synthetic/financials/alpha-1400-00' }),
  row({ id: 'financial-alpha-demand-1399-99', tenant: 'org-alpha', kind: 'financial', title: 'Synthetic Demand Below Boundary', legacyFields: ['Demand-1399-99'], active: true, deleted: false, financialYear: '2021-22', amountPaise: '139999999', sourceLink: '/synthetic/financials/alpha-1399-99' }),
  row({ id: 'client-beta-birch', tenant: 'org-beta', kind: 'client', title: 'Birch Synthetic', legacyFields: ['Birch Synthetic', 'GSTIN-SYN-BETA-99'], active: true, deleted: false, sourceLink: '/synthetic/clients/beta-birch' }),
  row({ id: 'matter-beta-private', tenant: 'org-beta', kind: 'matter', title: 'Beta Private', legacyFields: ['Beta Private', 'MAT-BETA-PRIVATE'], active: true, deleted: false, sourceLink: '/synthetic/matters/beta-private' }),
  row({ id: 'doc-beta-private-order', tenant: 'org-beta', kind: 'document', title: 'Beta Private Order', legacyFields: ['BETA-PRIVATE-ORDER', 'REF-BETA-9000'], active: true, deleted: false, legalAliases: ['section-6'], concepts: ['appeal'], contentAvailability: 'source_indexed', citation: { documentId: 'doc-beta-private-order', page: 1, anchor: 'private' }, sourceLink: '/synthetic/documents/beta-private' }),
  row({ id: 'passage-beta-private', tenant: 'org-beta', kind: 'passage', title: 'Beta Private Passage', legacyFields: ['BETA-PASSAGE'], active: true, deleted: false, sourceLink: '/synthetic/documents/beta-private#private' }),
  row({ id: 'financial-beta-private', tenant: 'org-beta', kind: 'financial', title: 'Beta Private Demand', legacyFields: ['BETA-DEMAND'], active: true, deleted: false, amountPaise: '999999', sourceLink: '/synthetic/financials/beta-private' }),
  row({ id: 'client-alpha-inactive', tenant: 'org-alpha', kind: 'client', title: 'Inactive Synthetic', legacyFields: ['legacy inactive'], active: false, deleted: false, sourceLink: '/synthetic/clients/inactive' }),
  row({ id: 'doc-alpha-deleted', tenant: 'org-alpha', kind: 'document', title: 'Deleted Synthetic', legacyFields: ['legacy deleted'], active: true, deleted: true, sourceLink: '/synthetic/documents/deleted' }),
  ...Array.from({ length: 11 }, (_, index) => row({ id: `client-alpha-cap-${index + 1}`, tenant: 'org-alpha', kind: 'client', title: `Synthetic Cap ${index + 1}`, legacyFields: ['legacy-cap'], active: true, deleted: false, sourceLink: `/synthetic/clients/cap-${index + 1}` })),
  ...Array.from({ length: 6 }, (_, index) => row({ id: `doc-alpha-vector-${index + 1}`, tenant: 'org-alpha', kind: 'document', title: `Synthetic Vector ${index + 1}`, legacyFields: [], active: true, deleted: false, contentAvailability: 'source_indexed', sourceLink: `/synthetic/documents/vector-${index + 1}`, semanticQueries: ['vector-cap'] })),
]
const cases: EvaluationCase[] = []
const add = (category: Category, query: string, resultIds: string[], constraints?: Constraints, notes?: string, absentResultIds?: string[]) => cases.push({ id: `${category}-${String(cases.length + 1).padStart(3, '0')}`, category, tenant: 'org-alpha', query, expected: { resultIds, ...(absentResultIds ? { absentResultIds } : {}), nonDisclosure: category === 'isolation' }, ...(constraints ? { constraints } : {}), ...(notes ? { notes } : {}) })
for (const [query, id] of [['MAT-ALPHA-AP-01', 'matter-alpha-appeal'], ['REF-ALPHA-1400', 'doc-alpha-notice-1400'], ['GSTIN-SYN-ALPHA-01', 'client-alpha-amber'], ['notice-1400.pdf', 'doc-alpha-notice-1400'], ['Appeal Amber', 'matter-alpha-appeal'], ['OCR-SCAN-ALPHA', 'doc-alpha-scan-ocr'], ['REGISTER-ALPHA-21', 'doc-alpha-import-register'], ['LIM-ALPHA-21', 'matter-alpha-limitation'], ['FY21-ALPHA', 'passage-alpha-fy-2021'], ['S6-ALPHA', 'passage-alpha-section-6'], ['Demand-1400-01', 'financial-alpha-demand-1400-01'], ['client amber', 'client-alpha-amber']] as const) add('exact', query, [id])
for (const query of ['section 6', 'Section 6', 's. 6', 'sec 6', 'Section 6(1)', 'section six', 'GST Act section 6', 'appeal under section 6', 'provision 6', 'legal section 6', 'Section-6', 's 6 appeal']) add('legal', query, ['passage-alpha-section-6'], { kind: 'passage', legalAlias: 'section-6' })
for (const query of ['natural justice', 'fair hearing', 'audi alteram partem', 'opportunity to be heard', 'procedural fairness', 'hearing denied', 'due process', 'right to respond', 'fair procedure', 'hearing opportunity', 'justice natural', 'no hearing']) add('synonym', query, ['doc-alpha-order-natural-justice'], { concept: 'natural-justice' })
for (const [query, operator, value, upperValue, ids] of [['demand > INR 14 lakh', 'gt', '140000000', undefined, ['financial-alpha-demand-1400-01']], ['demand greater than 14 lakh', 'gt', '140000000', undefined, ['financial-alpha-demand-1400-01']], ['demand above 14 lac', 'gt', '140000000', undefined, ['financial-alpha-demand-1400-01']], ['demand > 14L', 'gt', '140000000', undefined, ['financial-alpha-demand-1400-01']], ['demand > 0.14 crore', 'gt', '140000000', undefined, ['financial-alpha-demand-1400-01']], ['demand > 14 Cr', 'gt', '14000000000', undefined, []], ['demand = 14 lakh', 'eq', '140000000', undefined, ['financial-alpha-demand-1400-00']], ['demand >= 14 lakh', 'gte', '140000000', undefined, ['financial-alpha-demand-1400-01', 'financial-alpha-demand-1400-00']], ['demand < 14 lakh', 'lt', '140000000', undefined, ['financial-alpha-demand-1399-99']], ['demand <= 14 lakh', 'lte', '140000000', undefined, ['financial-alpha-demand-1400-00', 'financial-alpha-demand-1399-99']], ['demand > INR 1400000.00', 'gt', '140000000', undefined, ['financial-alpha-demand-1400-01']], ['demand > INR 1400000.01', 'gt', '140000001', undefined, []], ['demand = INR 1400000.00', 'eq', '140000000', undefined, ['financial-alpha-demand-1400-00']], ['demand = INR 1399999.99', 'eq', '139999999', undefined, ['financial-alpha-demand-1399-99']], ['demand > 140000000 paise', 'gt', '140000000', undefined, ['financial-alpha-demand-1400-01']], ['demand >= 140000000 paise', 'gte', '140000000', undefined, ['financial-alpha-demand-1400-01', 'financial-alpha-demand-1400-00']], ['demand > 1,400,000 rupees', 'gt', '140000000', undefined, ['financial-alpha-demand-1400-01']], ['demand > 14 lakh 1 paise', 'gt', '140000001', undefined, []], ['demand >= 13 lakh 99 thousand 999 rupees 99 paise', 'gte', '139999999', undefined, ['financial-alpha-demand-1400-01', 'financial-alpha-demand-1400-00', 'financial-alpha-demand-1399-99']], ['demand between 13.99 and 14 lakh', 'between', '139900000', '140000000', ['financial-alpha-demand-1400-00', 'financial-alpha-demand-1399-99']]] as const) add('numeric', query, [...ids], { kind: 'financial', amount: { operator, valuePaise: value, upperValuePaise: upperValue } })
for (const [query, constraints] of [['FY 2021-22', { kind: 'passage', financialYear: '2021-22' }], ['financial year 2021-22', { kind: 'passage', financialYear: '2021-22' }], ['FY21-22', { kind: 'passage', financialYear: '2021-22' }], ['orders in FY 2021-22', { kind: 'passage', financialYear: '2021-22' }], ['after 2021-04-01', { kind: 'passage', date: { operator: 'after', value: '2021-04-01' } }], ['before 2022-04-01', { kind: 'passage', date: { operator: 'before', value: '2022-04-01' } }], ['between 2021-04-01 and 2022-03-31', { kind: 'passage', date: { operator: 'between', value: '2021-04-01', upperValue: '2022-03-31' } }], ['dated 2021-07-15', { kind: 'passage', date: { operator: 'on', value: '2021-07-15' } }], ['date on 2021-07-15', { kind: 'passage', date: { operator: 'on', value: '2021-07-15' } }], ['limitation FY 2021-22', { kind: 'passage', financialYear: '2021-22' }], ['document date after 2021-04-01', { kind: 'passage', date: { operator: 'after', value: '2021-04-01' } }], ['document date before 2022-04-01', { kind: 'passage', date: { operator: 'before', value: '2022-04-01' } }]] as const) add('date-fy', query, ['passage-alpha-fy-2021'], { ...constraints, concept: 'limitation' })
add('compound', 'section 6 appeal FY 2021-22', ['passage-alpha-section-6'], { kind: 'passage', legalAlias: 'section-6', concept: 'appeal', financialYear: '2021-22' })
add('compound', 'natural justice order after 2021-04-01', ['doc-alpha-order-natural-justice'], { kind: 'document', concept: 'natural-justice', date: { operator: 'after', value: '2021-04-01' } })
add('compound', 'demand > 14L appeal', ['financial-alpha-demand-1400-01'], { kind: 'financial', concept: 'appeal', amount: { operator: 'gt', valuePaise: '140000000' } })
add('compound', 'metadata only FY 2021-22', ['doc-alpha-import-register'], { kind: 'document', availability: 'metadata_only', financialYear: '2021-22' })
add('compound', 'scanned order section 6', ['doc-alpha-scan-ocr'], { kind: 'document', availability: 'source_unreadable', legalAlias: 'section-6' })
add('compound', 'section 6 and demand >= 14 lakh', [], { legalAlias: 'section-6', amount: { operator: 'gte', valuePaise: '140000000' } })
add('compound', 'appeal with fair hearing', ['doc-alpha-order-natural-justice'], { kind: 'document', conceptsAll: ['appeal', 'natural-justice'] })
add('compound', 'FY 2021-22 demand = 14 lakh', ['financial-alpha-demand-1400-00'], { kind: 'financial', financialYear: '2021-22', amount: { operator: 'eq', valuePaise: '140000000' } })
add('compound', 'orders with section 6 before 2022-04-01', ['passage-alpha-section-6'], { legalAlias: 'section-6', date: { operator: 'before', value: '2022-04-01' } })
add('compound', 'client amber section 6', [], { kind: 'client', legalAlias: 'section-6' })
for (const [query, ids, availability] of [['OCR-SCAN-ALPHA', ['doc-alpha-scan-ocr'], 'source_unreadable'], ['scanned document metadata', ['doc-alpha-scan-ocr'], 'source_unreadable'], ['REGISTER-ALPHA-21', ['doc-alpha-import-register'], 'metadata_only'], ['metadata-only imported record', ['doc-alpha-import-register'], 'metadata_only'], ['passage in metadata-only record', [], 'metadata_only'], ['page text in unreadable scan', [], 'source_unreadable'], ['document with limited content search', ['doc-alpha-scan-ocr'], 'source_unreadable'], ['imported timeline FY 2021-22', ['doc-alpha-import-register'], 'metadata_only']] as const) add('availability', query, [...ids], { availability }, 'Limited-content sources may return metadata but never a body-passage match.')
for (const query of ['धारा 6 अपील', 'निष्पक्ष सुनवाई', 'section 6 की appeal', 'FY 2021-22 में आदेश', '14 लाख से अधिक demand', 'प्राकृतिक न्याय order', 'hearing का अवसर', 'appeal में section six']) add('multilingual', query, query.includes('14') ? ['financial-alpha-demand-1400-01'] : query.includes('FY') ? ['passage-alpha-fy-2021'] : query.includes('निष्पक्ष') || query.includes('प्राकृतिक') || query.includes('hearing') ? ['doc-alpha-order-natural-justice'] : ['passage-alpha-section-6'])
for (const query of ['zzzx unavailable evidence', 'DROP TABLE documents', '" OR 1=1 --', '<script>alert(1)</script>', 'GSTIN-SYN-BETA-99', 'unmapped legal clause 999', 'demand > not-a-number', 'FY 2099-00', 'x', '']) add('negative', query, [], undefined, 'No-result/error handling must disclose no inaccessible records.')
const betaIds = ['client-beta-birch', 'matter-beta-private', 'doc-beta-private-order', 'passage-beta-private', 'financial-beta-private']
for (const query of ['BETA-PRIVATE-ORDER', 'MAT-BETA-PRIVATE', 'GSTIN-SYN-BETA-99', 'private beta evidence', 'REF-BETA-9000', 'beta confidential order', 'section 6 beta private', 'demand beta private']) add('isolation', query, [], undefined, 'Zero results; no title, filename, snippet, vector, count, or timing/existence disclosure.', betaIds)
export const SEARCH_EVALUATION_CORPUS: Corpus = { version: CORPUS_VERSION, results, cases }

/** Faithful synthetic model of current searchAll, not captured database/RLS output. */
export function runLegacySearch(query: string, options: { tenant?: Tenant; hasCurrentOrg?: boolean; semantic?: boolean; semanticProvider?: 'available' | 'no_embedding' | 'rpc_error' } = {}): LegacyRun {
  const tenant = options.tenant ?? 'org-alpha'; const normalized = query.trim().toLowerCase()
  if (normalized.length < 2 || options.hasCurrentOrg === false) return { resultIds: [], usageLogged: false, semanticFallback: false }
  const lexical = (kind: 'client' | 'matter' | 'document') => results.filter((item) => item.tenant === tenant && item.kind === kind && item.active && !item.deleted && item.legacyFields.some((field) => field.toLowerCase().includes(normalized))).slice(0, 10)
  const ordered = [...lexical('client'), ...lexical('matter'), ...lexical('document')]
  if (!options.semantic) return { resultIds: ordered.map((item) => item.id), usageLogged: false, semanticFallback: false }
  if (options.semanticProvider === 'no_embedding') return { resultIds: ordered.map((item) => item.id), usageLogged: false, semanticFallback: false }
  if (options.semanticProvider === 'rpc_error') return { resultIds: ordered.map((item) => item.id), usageLogged: true, semanticFallback: true }
  const vectors = results.filter((item) => item.tenant === tenant && item.kind === 'document' && item.active && !item.deleted && item.semanticQueries?.includes(normalized)).slice(0, 5)
  return { resultIds: [...ordered, ...vectors.filter((vector) => !ordered.some((item) => item.id === vector.id))].map((item) => item.id), usageLogged: true, semanticFallback: false }
}
export const LEGACY_CONTRACT_RECORD = [
  { name: 'minimum query length', query: 'x', options: {}, expected: { resultIds: [], usageLogged: false, semanticFallback: false } },
  { name: 'absent current organisation', query: 'REF-ALPHA-1400', options: { hasCurrentOrg: false }, expected: { resultIds: [], usageLogged: false, semanticFallback: false } },
  { name: 'inactive rows are excluded', query: 'inactive', options: {}, expected: { resultIds: [], usageLogged: false, semanticFallback: false } },
  { name: 'deleted rows are excluded', query: 'deleted', options: {}, expected: { resultIds: [], usageLogged: false, semanticFallback: false } },
  { name: 'current tenant scope', query: 'BETA-PRIVATE-ORDER', options: {}, expected: { resultIds: [], usageLogged: false, semanticFallback: false } },
  { name: 'lexical entity order', query: 'REF-ALPHA-1400', options: {}, expected: { resultIds: ['doc-alpha-notice-1400'], usageLogged: false, semanticFallback: false } },
  { name: 'per-entity ten-row cap', query: 'legacy-cap', options: {}, expected: { resultIds: Array.from({ length: 10 }, (_, index) => `client-alpha-cap-${index + 1}`), usageLogged: false, semanticFallback: false } },
  { name: 'semantic default disabled', query: 'audi alteram partem', options: {}, expected: { resultIds: [], usageLogged: false, semanticFallback: false } },
  { name: 'semantic append and usage logging', query: 'audi alteram partem', options: { semantic: true }, expected: { resultIds: ['doc-alpha-order-natural-justice'], usageLogged: true, semanticFallback: false } },
  { name: 'missing semantic embedding keeps lexical results without usage', query: 'REF-ALPHA-1400', options: { semantic: true, semanticProvider: 'no_embedding' }, expected: { resultIds: ['doc-alpha-notice-1400'], usageLogged: false, semanticFallback: false } },
  { name: 'semantic RPC/fetch failure keeps lexical results after usage', query: 'REF-ALPHA-1400', options: { semantic: true, semanticProvider: 'rpc_error' }, expected: { resultIds: ['doc-alpha-notice-1400'], usageLogged: true, semanticFallback: true } },
  { name: 'vector RPC candidate limit is five', query: 'vector-cap', options: { semantic: true }, expected: { resultIds: ['doc-alpha-vector-1', 'doc-alpha-vector-2', 'doc-alpha-vector-3', 'doc-alpha-vector-4', 'doc-alpha-vector-5'], usageLogged: true, semanticFallback: false } },
] as const

function matchesAmount(actual: string | undefined, expected: NonNullable<Constraints['amount']>): boolean { if (!actual) return false; const left = BigInt(actual); const lower = BigInt(expected.valuePaise); if (expected.operator === 'between') { const upper = expected.upperValuePaise; return typeof upper === 'string' && left >= lower && left <= BigInt(upper) } return expected.operator === 'eq' ? left === lower : expected.operator === 'gt' ? left > lower : expected.operator === 'gte' ? left >= lower : expected.operator === 'lt' ? left < lower : left <= lower }
function matchesConstraints(item: Source, constraints?: Constraints): boolean {
  if (!constraints) return true
  if (constraints.kind && item.kind !== constraints.kind) return false
  if (constraints.legalAlias && !item.legalAliases?.includes(constraints.legalAlias)) return false
  if (constraints.concept && !item.concepts?.includes(constraints.concept)) return false
  if (constraints.conceptsAll && !constraints.conceptsAll.every((concept) => item.concepts?.includes(concept))) return false
  if (constraints.financialYear && item.financialYear !== constraints.financialYear) return false
  if (constraints.availability && item.contentAvailability !== constraints.availability) return false
  if (constraints.date && (!item.documentDate || (constraints.date.operator === 'on' ? item.documentDate !== constraints.date.value : constraints.date.operator === 'before' ? item.documentDate >= constraints.date.value : constraints.date.operator === 'after' ? item.documentDate <= constraints.date.value : !constraints.date.upperValue || item.documentDate < constraints.date.value || item.documentDate > constraints.date.upperValue))) return false
  return !constraints.amount || matchesAmount(item.amountPaise, constraints.amount)
}
function legalAliasFromQuery(query: string): string | undefined {
  const normalized = query.toLowerCase()
  return /(?:section|sec\.?|s\.?|provision)[\s-]*(?:6|six)/.test(normalized) ? 'section-6' : undefined
}
type SecureOutput = { resultIds: string[]; results: Array<{ id: string }> }
function queryMatches(item: Source, entry: EvaluationCase): boolean { if (entry.category === 'legal') return legalAliasFromQuery(entry.query) === entry.constraints?.legalAlias; if (entry.category === 'synonym') return item.semanticQueries?.includes(entry.query) ?? false; if (entry.category === 'exact' || entry.category === 'isolation') return item.legacyFields.some((field) => field.toLowerCase().includes(entry.query.toLowerCase())); if (entry.category === 'availability') return !/^(passage|page text)/.test(entry.query); return true }
function sourceCandidates(entry: EvaluationCase, sourceRows: Source[] = results): Source[] { return sourceRows.filter((item) => item.tenant === entry.tenant && item.active && !item.deleted && matchesConstraints(item, entry.constraints) && queryMatches(item, entry)) }
function evaluateSecureCase(entry: EvaluationCase, sourceRows: Source[] = results): SecureOutput { const resultIds = sourceCandidates(entry, sourceRows).map((item) => item.id); return { resultIds, results: resultIds.map((id) => ({ id })) } }
const tenants = new Set<Tenant>(['org-alpha', 'org-beta']); const categories = new Set<Category>(['exact', 'legal', 'synonym', 'numeric', 'date-fy', 'compound', 'availability', 'multilingual', 'negative', 'isolation'])
const kinds = new Set<Kind>(['client', 'matter', 'document', 'passage', 'financial']); const availabilityValues = new Set<Availability>(['source_indexed', 'metadata_only', 'source_unreadable']); const dateOperators = new Set(['on', 'before', 'after', 'between']); const amountOperators = new Set(['eq', 'gt', 'gte', 'lt', 'lte', 'between'])
const prohibited = [/\b\d{12}\b/, /\b[A-Z]{5}\d{4}[A-Z]\b/, /\b[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}\b/, /\b(?:\+91[- ]?)?[6-9]\d{9}\b/, /\b[0-3]\d[A-Z]{5}\d{4}[A-Z]\dZ[A-Z\d]\b/i, /\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b/i, /(?:api[_-]?key|secret|token|password)\s*[:=]/i]
function assert(condition: unknown, message: string): asserts condition { if (!condition) throw new Error(message) }
function assertThrows(action: () => void, message: string): void { let thrown = false; try { action() } catch { thrown = true }; assert(thrown, message) }
function equal(left: unknown, right: unknown): boolean { return JSON.stringify(left) === JSON.stringify(right) }
function record(value: unknown): value is Record<string, unknown> { return Boolean(value) && typeof value === 'object' && !Array.isArray(value) }
function exactKeys(value: Record<string, unknown>, permitted: string[], label: string): void { assert(Object.keys(value).every((key) => permitted.includes(key)), `Unknown ${label} key`) }
function has(value: Record<string, unknown>, key: string): boolean { return Object.prototype.hasOwnProperty.call(value, key) }
function validDate(value: unknown): value is string { if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return false; const parsed = new Date(`${value}T00:00:00.000Z`); return !Number.isNaN(parsed.valueOf()) && parsed.toISOString().slice(0, 10) === value }
function validateConstraints(constraints: unknown, caseId: string): void {
  if (constraints === undefined) return
  assert(record(constraints), `Malformed constraints on ${caseId}`); exactKeys(constraints, ['kind', 'legalAlias', 'concept', 'conceptsAll', 'financialYear', 'date', 'amount', 'availability'], `constraint on ${caseId}`)
  if ('kind' in constraints) assert(typeof constraints.kind === 'string' && kinds.has(constraints.kind as Kind), `Unknown constraint kind on ${caseId}`)
  if ('legalAlias' in constraints) assert(typeof constraints.legalAlias === 'string', `Malformed legal alias on ${caseId}`)
  if ('concept' in constraints) assert(typeof constraints.concept === 'string', `Malformed concept on ${caseId}`)
  if ('conceptsAll' in constraints) assert(Array.isArray(constraints.conceptsAll) && constraints.conceptsAll.length > 0 && constraints.conceptsAll.every((value) => typeof value === 'string'), `Malformed concept set on ${caseId}`)
  if ('financialYear' in constraints) assert(typeof constraints.financialYear === 'string' && /^\d{4}-\d{2}$/.test(constraints.financialYear), `Malformed FY on ${caseId}`)
  if ('availability' in constraints) assert(typeof constraints.availability === 'string' && availabilityValues.has(constraints.availability as Availability), `Unknown availability on ${caseId}`)
  for (const [name, upper] of [['date', 'upperValue'], ['amount', 'upperValuePaise']] as const) if (has(constraints, name)) { const value = constraints[name]; assert(record(value), `Malformed ${name} constraint on ${caseId}`); exactKeys(value, ['operator', name === 'date' ? 'value' : 'valuePaise', upper], `${name} constraint on ${caseId}`); assert(typeof value.operator === 'string' && (name === 'date' ? dateOperators : amountOperators).has(value.operator), `Unknown ${name} operator on ${caseId}`); const primary = name === 'date' ? value.value : value.valuePaise; assert(name === 'date' ? validDate(primary) : typeof primary === 'string' && /^\d+$/.test(primary), `Malformed ${name} value on ${caseId}`); if (value.operator === 'between') { const bound = value[upper]; assert(name === 'date' ? validDate(bound) : typeof bound === 'string' && /^\d+$/.test(bound), `Missing ${name} upper bound on ${caseId}`); assert(name === 'date' ? (primary as string) <= (bound as string) : BigInt(primary as string) <= BigInt(bound as string), `Invalid ${name} range on ${caseId}`) } else assert(value[upper] === undefined, `Unexpected ${name} upper bound on ${caseId}`) }
}
export function validateSearchEvaluationCorpus(corpus: Corpus = SEARCH_EVALUATION_CORPUS): void {
  assert(corpus.version === CORPUS_VERSION, 'Corpus version is not pinned'); assert(corpus.cases.length >= 100, `Corpus must have at least 100 cases; found ${corpus.cases.length}`)
  const ids = new Set<string>(); const byId = new Map<string, Source>()
  for (const item of corpus.results) { assert(record(item), 'Malformed source'); exactKeys(item, ['id', 'tenant', 'kind', 'title', 'legacyFields', 'active', 'deleted', 'legalAliases', 'concepts', 'documentDate', 'financialYear', 'amountPaise', 'contentAvailability', 'citation', 'sourceLink', 'semanticQueries'], `source ${item.id}`); assert(typeof item.id === 'string' && !ids.has(item.id), `Duplicate or malformed result fixture ID`); ids.add(item.id); byId.set(item.id, item as Source); assert(tenants.has(item.tenant as Tenant), `Unknown result tenant: ${item.id}`); assert(kinds.has(item.kind as Kind), `Unknown source kind: ${item.id}`); assert(typeof item.title === 'string' && Array.isArray(item.legacyFields) && item.legacyFields.every((value) => typeof value === 'string') && typeof item.active === 'boolean' && typeof item.deleted === 'boolean' && typeof item.sourceLink === 'string', `Malformed source fields: ${item.id}`); assert(item.sourceLink.startsWith('/synthetic/'), `Non-synthetic source link: ${item.id}`); if (has(item, 'legalAliases')) assert(Array.isArray(item.legalAliases) && item.legalAliases.every((value) => typeof value === 'string'), `Malformed legal aliases: ${item.id}`); if (has(item, 'concepts')) assert(Array.isArray(item.concepts) && item.concepts.every((value) => typeof value === 'string'), `Malformed concepts: ${item.id}`); if (has(item, 'semanticQueries')) assert(Array.isArray(item.semanticQueries) && item.semanticQueries.every((value) => typeof value === 'string'), `Malformed semantic queries: ${item.id}`); if (has(item, 'documentDate')) assert(validDate(item.documentDate), `Malformed document date: ${item.id}`); if (has(item, 'financialYear')) assert(typeof item.financialYear === 'string' && /^\d{4}-\d{2}$/.test(item.financialYear), `Malformed source FY: ${item.id}`); if (has(item, 'amountPaise')) assert(typeof item.amountPaise === 'string' && /^\d+$/.test(item.amountPaise), `Malformed source paise: ${item.id}`); if (has(item, 'contentAvailability')) assert(typeof item.contentAvailability === 'string' && availabilityValues.has(item.contentAvailability as Availability), `Unknown source availability: ${item.id}`); if (item.contentAvailability && item.contentAvailability !== 'source_indexed') assert(item.kind === 'document', `Limited content availability must be a document: ${item.id}`); if (has(item, 'citation')) { assert(record(item.citation), `Malformed citation: ${item.id}`); exactKeys(item.citation, ['documentId', 'page', 'anchor'], `citation ${item.id}`); assert(typeof item.citation.documentId === 'string' && Number.isInteger(item.citation.page) && item.citation.page > 0 && typeof item.citation.anchor === 'string', `Malformed citation fields: ${item.id}`) } if (item.kind === 'financial') assert(/^\d+$/.test(item.amountPaise ?? ''), `Financial fixture ${item.id} needs integer paise`) }
  const caseIds = new Set<string>(); const coverage = new Set<Category>()
  for (const entry of corpus.cases) {
    assert(record(entry), 'Malformed case'); exactKeys(entry, ['id', 'category', 'tenant', 'query', 'expected', 'constraints', 'notes'], `case ${entry.id}`); assert(typeof entry.id === 'string' && !caseIds.has(entry.id), `Duplicate or malformed evaluation case ID`); caseIds.add(entry.id); assert(tenants.has(entry.tenant as Tenant), `Unknown case tenant: ${entry.id}`); assert(categories.has(entry.category as Category), `Unsupported category on ${entry.id}`); coverage.add(entry.category as Category); assert(typeof entry.query === 'string' && record(entry.expected) && Array.isArray(entry.expected.resultIds) && entry.expected.resultIds.every((value) => typeof value === 'string'), `Malformed case: ${entry.id}`); exactKeys(entry.expected, ['resultIds', 'absentResultIds', 'nonDisclosure'], `expected on ${entry.id}`); if (has(entry.expected, 'absentResultIds')) assert(Array.isArray(entry.expected.absentResultIds) && entry.expected.absentResultIds.every((value) => typeof value === 'string'), `Malformed absent results on ${entry.id}`); if (has(entry.expected, 'nonDisclosure')) assert(typeof entry.expected.nonDisclosure === 'boolean', `Malformed non-disclosure on ${entry.id}`); if (has(entry, 'notes')) assert(typeof entry.notes === 'string', `Malformed notes on ${entry.id}`); validateConstraints(entry.constraints, entry.id); assert(new Set(entry.expected.resultIds).size === entry.expected.resultIds.length, `Duplicate expected result on ${entry.id}`); assert(new Set(entry.expected.absentResultIds ?? []).size === (entry.expected.absentResultIds?.length ?? 0), `Duplicate absent result on ${entry.id}`)
    for (const id of entry.expected.resultIds) {
      const item = byId.get(id); assert(item, `Unknown expected result ${id} on ${entry.id}`); assert(item.tenant === entry.tenant, `Cross-tenant expected inclusion ${id} on ${entry.id}`); assert(matchesConstraints(item, entry.constraints), `Expected result ${id} does not meet constraints on ${entry.id}`)
      if (entry.category === 'legal') { const alias = entry.constraints?.legalAlias; if (!alias) throw new Error(`Legal constraints missing on ${entry.id}`); assert(legalAliasFromQuery(entry.query) === alias && item.legalAliases?.includes(alias), `Legal alias does not match ${entry.id}`) }
      if (entry.category === 'synonym') assert(item.semanticQueries?.includes(entry.query), `Synonym query has no synthetic semantic reference on ${entry.id}`)
      if (entry.category === 'availability' && item.contentAvailability !== 'source_indexed') assert(item.kind === 'document', `Limited-content result claims a passage on ${entry.id}`)
    }
    for (const id of entry.expected.absentResultIds ?? []) { const item = byId.get(id); assert(item, `Unknown absent result ${id} on ${entry.id}`); assert(item.tenant !== entry.tenant, `Absent result ${id} is not foreign on ${entry.id}`) }
    const derived = sourceCandidates(entry, corpus.results).map((item) => item.id); if (entry.constraints && ['legal', 'synonym', 'numeric', 'date-fy', 'compound', 'availability'].includes(entry.category)) assert(equal(derived, entry.expected.resultIds), `Source-derived candidates differ from expected results on ${entry.id}`)
    if (entry.category === 'isolation') { assert(entry.expected.resultIds.length === 0 && entry.expected.nonDisclosure === true && (entry.expected.absentResultIds?.length ?? 0) > 0, `Isolation assertion malformed: ${entry.id}`); const output = evaluateSecureCase(entry, corpus.results); assert(output.resultIds.length === 0 && output.results.length === 0, `Foreign result disclosed on ${entry.id}`); assert(!/(title|filename|snippet|vector|count|timing|existence)/i.test(JSON.stringify(output)), `Disclosure-shaped output on ${entry.id}`) }
  }
  for (const category of categories) assert(coverage.has(category), `Missing required coverage: ${category}`)
  for (const pattern of prohibited) assert(!pattern.test(JSON.stringify(corpus)), `Potentially sensitive fixture value matches ${pattern}`)
  assert(corpus.cases.some((entry) => entry.category === 'numeric' && entry.query.includes('paise')), 'Missing paise-safe coverage'); assert(corpus.cases.some((entry) => entry.category === 'numeric' && /lakh|lac|14L|crore|Cr/.test(entry.query)), 'Missing Indian-unit coverage')
  for (const record of LEGACY_CONTRACT_RECORD) assert(equal(runLegacySearch(record.query, record.options), record.expected), `Legacy contract failed: ${record.name}`)
}
function runMutationChecks(): void {
  const clone = () => structuredClone(SEARCH_EVALUATION_CORPUS)
  const duplicateAbsent = clone(); duplicateAbsent.cases.find((entry) => entry.category === 'isolation')!.expected.absentResultIds!.push('client-beta-birch'); assertThrows(() => validateSearchEvaluationCorpus(duplicateAbsent), 'Duplicate absent mutation was accepted')
  const unknownTenant = clone(); unknownTenant.results[0].tenant = 'org-unknown' as Tenant; assertThrows(() => validateSearchEvaluationCorpus(unknownTenant), 'Unknown result tenant mutation was accepted')
  const localAbsent = clone(); localAbsent.cases.find((entry) => entry.category === 'isolation')!.expected.absentResultIds![0] = 'client-alpha-amber'; assertThrows(() => validateSearchEvaluationCorpus(localAbsent), 'Local absent mutation was accepted')
  const unknownResult = clone(); unknownResult.cases[0].expected.resultIds[0] = 'missing-source'; assertThrows(() => validateSearchEvaluationCorpus(unknownResult), 'Unknown expected-result mutation was accepted')
  const missingExpected = clone(); missingExpected.cases.find((entry) => entry.category === 'compound')!.expected.resultIds = []; assertThrows(() => validateSearchEvaluationCorpus(missingExpected), 'Missing source-derived expected result mutation was accepted')
  const missingSource = clone(); missingSource.results = missingSource.results.filter((item) => item.id !== 'passage-alpha-section-6'); assertThrows(() => validateSearchEvaluationCorpus(missingSource), 'Missing source mutation was accepted')
  const nullOptionalSource = clone(); (nullOptionalSource.results[0] as unknown as Record<string, unknown>).legalAliases = null; assertThrows(() => validateSearchEvaluationCorpus(nullOptionalSource), 'Null optional source field was accepted')
  const malformedCitation = clone(); (malformedCitation.results.find((item) => item.citation)!.citation as unknown as Record<string, unknown>).page = 0; assertThrows(() => validateSearchEvaluationCorpus(malformedCitation), 'Malformed citation was accepted')
  const nullNotes = clone(); (nullNotes.cases[0] as unknown as Record<string, unknown>).notes = null; assertThrows(() => validateSearchEvaluationCorpus(nullNotes), 'Null notes were accepted')
  const invalidCalendarDate = clone(); (invalidCalendarDate.cases.find((entry) => entry.constraints?.date)!.constraints!.date as unknown as Record<string, unknown>).value = '2021-02-30'; assertThrows(() => validateSearchEvaluationCorpus(invalidCalendarDate), 'Invalid calendar date was accepted')
  const reversedDateRange = clone(); const dateRange = reversedDateRange.cases.find((entry) => entry.constraints?.date?.operator === 'between')!.constraints!.date!; dateRange.value = '2022-03-31'; dateRange.upperValue = '2021-04-01'; assertThrows(() => validateSearchEvaluationCorpus(reversedDateRange), 'Reversed date range was accepted')
  const reversedAmountRange = clone(); const amountRange = reversedAmountRange.cases.find((entry) => entry.constraints?.amount?.operator === 'between')!.constraints!.amount!; amountRange.valuePaise = '140000001'; amountRange.upperValuePaise = '140000000'; assertThrows(() => validateSearchEvaluationCorpus(reversedAmountRange), 'Reversed amount range was accepted')
}
validateSearchEvaluationCorpus(); runMutationChecks()
console.log(`PASS ${CORPUS_VERSION}: ${cases.length} deterministic anonymised cases across ${new Set(cases.map((entry) => entry.category)).size} categories; legacy contract and mutation checks passed`)
