'use server'

import { createClient } from '@/lib/supabase/server'
import { getCurrentOrgId } from './org'
import { revalidatePath } from 'next/cache'

// ── Types ─────────────────────────────────────────────────────────

import { MatterStatus, FINANCIAL_YEARS } from '../constants'

// ── Read Matters ──────────────────────────────────────────────────

export async function getMatters() {
  const supabase = await createClient()
  const orgId = await getCurrentOrgId()
  if (!orgId) return []

  const { data } = await supabase
    .from('matters')
    .select(`
      *,
      clients(id, name, gstin)
    `)
    .eq('org_id', orgId)
    .is('deleted_at', null)
    .order('created_at', { ascending: false })

  return data ?? []
}

export async function getMattersByClient(clientId: string) {
  const supabase = await createClient()
  const orgId = await getCurrentOrgId()
  if (!orgId) return []

  const { data } = await supabase
    .from('matters')
    .select('*')
    .eq('org_id', orgId)
    .eq('client_id', clientId)
    .is('deleted_at', null)
    .order('created_at', { ascending: false })

  return data ?? []
}

export async function getMatterById(id: string) {
  const supabase = await createClient()
  const orgId = await getCurrentOrgId()
  if (!orgId) return null

  const { data } = await supabase
    .from('matters')
    .select(`
      *,
      clients(id, name, gstin, pan)
    `)
    .eq('id', id)
    .eq('org_id', orgId)
    .is('deleted_at', null)
    .single()

  return data
}

// ── Create Matter ─────────────────────────────────────────────────

export async function createMatter(formData: FormData) {
  const supabase = await createClient()
  const orgId = await getCurrentOrgId()
  if (!orgId) return { error: 'No active organisation.' }

  const clientId = formData.get('client_id') as string
  const title = (formData.get('title') as string)?.trim()
  const financialYear = formData.get('financial_year') as string
  const description = (formData.get('description') as string)?.trim() || null
  const status = (formData.get('status') as MatterStatus) || 'active'

  if (!clientId) return { error: 'Client is required.' }
  if (!title || title.length < 2) return { error: 'Title must be at least 2 characters.' }
  if (!financialYear) return { error: 'Financial year is required.' }
  if (!FINANCIAL_YEARS.includes(financialYear)) {
    return { error: 'Please select a valid financial year.' }
  }

  // Verify client belongs to this org
  const { data: client } = await supabase
    .from('clients')
    .select('id')
    .eq('id', clientId)
    .eq('org_id', orgId)
    .single()

  if (!client) return { error: 'Client not found.' }

  const { data, error } = await supabase
    .from('matters')
    .insert({
      org_id: orgId,
      client_id: clientId,
      title,
      financial_year: financialYear,
      description,
      status,
      // matter_code is auto-generated by DB trigger
    })
    .select('id, matter_code')
    .single()

  if (error || !data) {
    console.error('Create matter error:', error)
    return { error: error?.message ?? 'Failed to create matter.' }
  }

  revalidatePath('/matters')
  revalidatePath(`/clients/${clientId}`)
  return { success: true, id: data.id, matterCode: data.matter_code }
}

// ── Update Matter ─────────────────────────────────────────────────

export async function updateMatter(id: string, formData: FormData) {
  const supabase = await createClient()
  const orgId = await getCurrentOrgId()
  if (!orgId) return { error: 'No active organisation.' }

  const title = (formData.get('title') as string)?.trim()
  const description = (formData.get('description') as string)?.trim() || null
  const status = formData.get('status') as MatterStatus | null

  if (!title || title.length < 2) return { error: 'Title must be at least 2 characters.' }

  const { error } = await supabase
    .from('matters')
    .update({
      title,
      description,
      ...(status ? { status } : {}),
    })
    .eq('id', id)
    .eq('org_id', orgId)

  if (error) {
    console.error('Update matter error:', error)
    return { error: error.message }
  }

  revalidatePath('/matters')
  revalidatePath(`/matters/${id}`)
  return { success: true }
}

// ── Archive / Close Matter ────────────────────────────────────────

export async function setMatterStatus(id: string, status: MatterStatus) {
  const supabase = await createClient()
  const orgId = await getCurrentOrgId()
  if (!orgId) return { error: 'No active organisation.' }

  const { error } = await supabase
    .from('matters')
    .update({ status })
    .eq('id', id)
    .eq('org_id', orgId)

  if (error) {
    console.error('Set matter status error:', error)
    return { error: error.message }
  }

  revalidatePath('/matters')
  revalidatePath(`/matters/${id}`)
  return { success: true }
}
