import { expect, test, type Page } from '@playwright/test'
import { launchChromiumPageZoom } from './chromium-page-zoom'
import { spawn, spawnSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const reason500 = 'Confirm the cited source and explain the discrepancy. '.repeat(10).slice(0, 500)
const dbArgs = ['exec', '-i', 'supabase_db_dms-review-153', 'psql', '-X', '-qAt', '-v', 'ON_ERROR_STOP=1', '-U', 'postgres', '-d', 'postgres']
function assertDisposable() {
  const workdir = process.env.REVIEW_ACCEPTANCE_WORKDIR
  if (!workdir || !readFileSync(join(workdir, 'supabase/config.toml'), 'utf8').includes('project_id = "dms-review-153"')) throw new Error('Browser faults require the owned disposable Review database.')
}
function db(sql: string) {
  assertDisposable()
  const result = spawnSync('docker', dbArgs, { input: sql, encoding: 'utf8', timeout: 15000 })
  if (result.status !== 0) throw new Error(result.stderr)
  return result.stdout
}

async function login(page: Page, user = 1) {
  await page.goto('/login')
  await page.getByLabel('Email address').fill(`review-${user}@example.test`)
  await page.getByLabel('Password').fill('ReviewFixture153!')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
}
async function noOverflow(page: Page) {
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.body.scrollWidth <= innerWidth)).toBe(true)
}
test('possible duplicate exact PDF comparison records both interpretations without document mutation',async({page,browser})=>{
  async function referenceLogin(target:Page,email:string){
    await target.goto('/login')
    await target.getByLabel('Email address').fill(email)
    await target.getByLabel('Password').fill('PlacementFixture167!')
    await target.getByRole('button',{name:'Sign in'}).click()
    await expect(target).toHaveURL(/\/dashboard$/)
  }
  const viewer=await browser.newContext({viewport:{width:320,height:740},colorScheme:'dark'})
  const viewerPage=await viewer.newPage()
  await referenceLogin(viewerPage,'reference-viewer@example.test')
  await viewerPage.goto('/review?type=possible_duplicate')
  await viewerPage.getByRole('button',{name:'Compare 2 documents'}).click()
  await expect(viewerPage.getByText('Exact official key in 2 current PDFs')).toBeVisible()
  await expect(viewerPage.getByRole('link',{name:'Open exact PDF source · Page 1'})).toHaveCount(2)
  for(const link of await viewerPage.getByRole('link',{name:'Open exact PDF source · Page 1'}).all())
    await expect(link).toHaveAttribute('href',/\/documents\/152e0000.*version=15200000.*page=1/)
  await viewerPage.getByRole('button',{name:'View decision'}).click()
  await expect(viewerPage.getByRole('button',{name:'Review document interpretation'})).toHaveCount(0)
  await noOverflow(viewerPage)
  await viewer.close()
  await page.setViewportSize({width:320,height:740})
  await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'})
  await referenceLogin(page,'reference-owner@example.test')
  await page.goto('/review?type=possible_duplicate')
  await page.getByRole('button',{name:'Compare 2 documents'}).click()
  await expect(page.getByRole('link',{name:'Open exact PDF source · Page 1'})).toHaveCount(2)
  await expect(page.getByRole('link',{name:'Inspect version in Workbench'})).toHaveCount(2)
  const sourceLinks=await Promise.all((await page.getByRole('link',{name:'Open exact PDF source · Page 1'}).all()).map(link=>link.getAttribute('href')))
  expect(new Set(sourceLinks).size).toBe(2)
  for(const href of sourceLinks){
    expect(href).toMatch(/\/documents\/152e0000.*version=15200000.*page=1/)
    await page.goto(href!)
    await expect(page.getByText('PDF source · Version 1 · Page 1 of 1')).toBeVisible()
    await expect(page.locator('[data-pdf-page="1"] canvas')).toBeVisible()
    await expect(page.getByText(/PDF source permanently unavailable|PDF could not be opened|Signed link expired/)).toHaveCount(0)
    await page.goBack()
    await expect(page.getByRole('heading',{name:'Compare 2 documents'})).toBeVisible()
  }
  await page.getByRole('tab',{name:'Evidence'}).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab',{name:'Decision'})).toBeFocused()
  await page.getByRole('radio',{name:/Mark all as distinct documents/}).check()
  await page.getByRole('button',{name:'Review document interpretation'}).click()
  await expect(page.getByRole('dialog')).toContainText('every document, source, filing and effective fact remains untouched')
  await page.getByLabel('Reason',{exact:true}).fill('This later order is a distinct current document using the same official key.')
  await page.getByRole('button',{name:'Record distinct documents'}).click()
  await expect(page.getByRole('heading',{name:'Distinct documents recorded'})).toBeVisible()
  await expect(page.getByText(/unchanged full source set will not raise Review again/)).toBeVisible()
  await noOverflow(page)
  db(`DO $$ DECLARE actor uuid:='152a0000-0000-0000-0000-000000000001'; r record; identifier_id uuid; candidate_id uuid; revision_value bigint; BEGIN
    PERFORM set_config('request.jwt.claim.role','authenticated',true);
    PERFORM set_config('request.jwt.claim.sub',actor::text,true);
    PERFORM set_config('request.jwt.claims',jsonb_build_object('role','authenticated','sub',actor,'iat',extract(epoch FROM now())::bigint)::text,true);
    SELECT id INTO identifier_id FROM public.document_self_identifiers WHERE document_id='152e0000-0000-0000-0000-000000000002' AND lifecycle_state='active' AND normalized_value='GST/555/2026';
    SELECT lifecycle_revision INTO revision_value FROM public.documents WHERE id='152e0000-0000-0000-0000-000000000002';
    SELECT * INTO r FROM public.revoke_document_self_identifier(identifier_id,1,revision_value,'Browser new-source revision fixture','15260000-0000-0000-0000-000000000018');
    IF r.code<>'ok' THEN RAISE EXCEPTION 'fixture revoke failed: %',r.code; END IF;
    SELECT id INTO candidate_id FROM public.document_field_candidates WHERE document_id='152e0000-0000-0000-0000-000000000002' AND field_path='document.official_reference.self_identifier' AND normalized_value->>'normalized_value'='GST/555/2026';
    SELECT lifecycle_revision INTO revision_value FROM public.documents WHERE id='152e0000-0000-0000-0000-000000000002';
    SELECT * INTO r FROM public.activate_document_self_identifier(candidate_id,revision_value,NULL,'15260000-0000-0000-0000-000000000019');
    IF r.code<>'ok' THEN RAISE EXCEPTION 'fixture activation failed: %',r.code; END IF;
  END $$;`)
  await page.setViewportSize({width:1440,height:900})
  await page.emulateMedia({colorScheme:'light',reducedMotion:'no-preference'})
  await page.goto('/review?type=possible_duplicate&status=needs_review')
  await page.getByRole('button',{name:'Compare 2 documents'}).click()
  await page.getByRole('button',{name:'View decision'}).click()
  await page.getByRole('radio',{name:/Mark a selected subset as possibly the same document/}).check()
  await page.getByRole('button',{name:'Review document interpretation'}).click()
  await expect(page.getByRole('dialog')).toContainText('No merge, deletion, move, replacement or effective-fact change')
  await page.getByLabel('Reason',{exact:true}).fill('Investigate the shared printed identity in a separate governed workflow.')
  await page.getByRole('button',{name:'Record possible same document'}).click()
  await expect(page.getByRole('heading',{name:'Possible same document recorded'})).toBeVisible()
  await expect(page.getByText(/Every cited PDF version and logical document remains separate and unchanged/)).toBeVisible()
  await page.getByRole('tab',{name:'Evidence'}).click()
  await expect(page.getByRole('link',{name:'Open exact PDF source · Page 1'})).toHaveCount(2)
  await noOverflow(page)
})
test('grouped possible duplicate exact PDF comparison names only a selected subset without mutation',async({page,browser})=>{
  async function signIn(target:Page,email:string){
    await target.goto('/login')
    await target.getByLabel('Email address').fill(email)
    await target.getByLabel('Password').fill('PlacementFixture167!')
    await target.getByRole('button',{name:'Sign in'}).click()
    await expect(target).toHaveURL(/\/dashboard$/)
  }
  const viewer=await browser.newContext({viewport:{width:320,height:740},colorScheme:'dark'})
  const viewerPage=await viewer.newPage()
  await signIn(viewerPage,'reference-viewer@example.test')
  await viewerPage.goto('/review?type=possible_duplicate')
  await viewerPage.getByRole('button',{name:'Compare 3 documents'}).click()
  await expect(viewerPage.getByText('Exact official key in 3 current PDFs')).toBeVisible()
  await expect(viewerPage.getByRole('link',{name:'Open exact PDF source · Page 1'})).toHaveCount(3)
  await viewerPage.getByRole('button',{name:'View decision'}).click()
  await expect(viewerPage.getByRole('button',{name:'Review document interpretation'})).toHaveCount(0)
  await noOverflow(viewerPage)
  await viewer.close()
  await page.setViewportSize({width:1440,height:900})
  await page.emulateMedia({colorScheme:'light',reducedMotion:'reduce'})
  await signIn(page,'reference-owner@example.test')
  await page.goto('/review?type=possible_duplicate')
  await page.getByRole('button',{name:'Compare 3 documents'}).click()
  await expect(page.getByRole('link',{name:'Open exact PDF source · Page 1'})).toHaveCount(3)
  const links=await Promise.all((await page.getByRole('link',{name:'Open exact PDF source · Page 1'}).all()).map(link=>link.getAttribute('href')))
  expect(new Set(links).size).toBe(3)
  for(const href of links){
    expect(href).toMatch(/\/documents\/152e0000.*version=15200000.*page=1/)
    await page.goto(href!)
    await expect(page.getByText('PDF source · Version 1 · Page 1 of 1')).toBeVisible()
    await expect(page.locator('[data-pdf-page="1"] canvas')).toBeVisible()
    await expect(page.getByText(/PDF source permanently unavailable|PDF could not be opened|Signed link expired/)).toHaveCount(0)
    await page.goBack()
    await expect(page.getByRole('heading',{name:'Compare 3 documents'})).toBeVisible()
  }
  await page.getByRole('button',{name:'View decision'}).click()
  await page.getByRole('radio',{name:/Mark a selected subset as possibly the same document/}).check()
  await expect(page.getByRole('button',{name:'Review document interpretation'})).toBeDisabled()
  await page.getByRole('checkbox',{name:/Reference 1/}).check()
  await page.getByRole('checkbox',{name:/Reference 2/}).check()
  await page.getByRole('button',{name:'Review document interpretation'}).click()
  await expect(page.getByRole('dialog')).toContainText('No relation to any unselected source is inferred')
  await expect(page.getByRole('dialog')).not.toContainText('Reference 3 (')
  await page.getByLabel('Reason',{exact:true}).fill('The first two cited exact PDFs warrant a possible-same investigation; no finding for the third.')
  await page.getByRole('button',{name:'Record possible same document'}).click()
  await expect(page.getByRole('heading',{name:'Possible same document recorded'})).toBeVisible()
  await expect(page.getByText('Selected possible-same documents')).toBeVisible()
  await expect(page.getByText(/No relationship to an unselected member is inferred/)).toBeVisible()
  await noOverflow(page)
})
test('multiple filed Matter conflicts require one printed target, current impact and human Move on mobile and desktop',async({page,browser})=>{
  async function placementLogin(target:Page,email:string){
    await target.goto('/login')
    await target.getByLabel('Email address').fill(email)
    await target.getByLabel('Password').fill('PlacementFixture167!')
    await target.getByRole('button',{name:'Sign in'}).click()
    await expect(target).toHaveURL(/\/dashboard$/)
  }
  const viewer=await browser.newContext({viewport:{width:320,height:740},colorScheme:'dark'})
  const viewerPage=await viewer.newPage()
  await placementLogin(viewerPage,'reference-viewer@example.test')
  await viewerPage.goto('/review?type=multi_placement_conflict')
  await viewerPage.getByRole('button',{name:'Review current filing'}).click()
  await expect(viewerPage.getByText('Printed sources and verified Matter candidates')).toBeVisible()
  await expect(viewerPage.getByText(/GST\/555\/2026/).first()).toBeVisible()
  await expect(viewerPage.getByText(/GST\/556\/2026/).first()).toBeVisible()
  await viewerPage.getByRole('button',{name:'View decision'}).click()
  await expect(viewerPage.getByRole('button',{name:'Review filing decision'})).toHaveCount(0)
  await noOverflow(viewerPage)
  await viewer.close()
  await page.setViewportSize({width:320,height:740})
  await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'})
  await placementLogin(page,'reference-owner@example.test')
  await page.goto('/review?type=multi_placement_conflict')
  await page.getByRole('button',{name:'Review current filing'}).click()
  await expect(page.getByText('Currently filed in Reference A')).toBeVisible()
  await expect(page.getByRole('link',{name:'Open exact source · Page 1'})).toHaveCount(2)
  await noOverflow(page)
  await page.getByRole('tab',{name:'Evidence'}).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab',{name:'Decision'})).toBeFocused()
  await page.getByRole('radio',{name:/Move to Reference B/}).check()
  await expect(page.getByText(/Current impact: Reference 2.*Reference B/)).toBeVisible()
  await page.getByRole('radio',{name:/Move to Reference C/}).check()
  await expect(page.getByText(/Current impact: Reference 2.*Reference B/)).toHaveCount(0)
  await expect(page.getByText(/Current impact: Reference 2/)).toBeVisible()
  await expect(page.getByText('No current blockers. Changed dependencies invalidate this preview.')).toBeVisible()
  await page.getByRole('button',{name:'Review filing decision'}).click()
  await expect(page.getByRole('dialog')).toContainText('Move Reference 2 from Reference A to Reference C')
  await page.getByLabel('Reason',{exact:true}).fill('Checked printed GST/556 source and current impact for this one verified Matter.')
  await page.getByRole('button',{name:'Move document'}).click()
  await expect(page.getByRole('heading',{name:'Document moved'})).toBeVisible()
  await expect(page.getByText('This Review item is closed.')).toBeVisible()
  await noOverflow(page)
  await page.setViewportSize({width:1440,height:900})
  await page.getByRole('tab',{name:'Evidence'}).click()
  await expect(page.getByText(/Live current filing: Reference C/)).toBeVisible()
  await page.getByRole('link',{name:'Open exact source · Page 1'}).nth(1).click()
  await expect(page).toHaveURL(/\/documents\/152e0000-0000-0000-0000-000000000002\?.*version=15200000-0000-0000-0000-000000000002.*page=1/)
  await expect(page.getByText('PDF source · Version 1 · Page 1 of 1')).toBeVisible()
  await expect(page.getByRole('link',{name:'Back to Matter'})).toHaveAttribute('href','/matters/169d0000-0000-0000-0000-000000000003')
  await noOverflow(page)
})
test('placed document conflict keeps or moves only after exact source and current impact on desktop and mobile',async({page,browser})=>{
  async function placementLogin(target:Page,email:string){
    await target.goto('/login')
    await target.getByLabel('Email address').fill(email)
    await target.getByLabel('Password').fill('PlacementFixture167!')
    await target.getByRole('button',{name:'Sign in'}).click()
    await expect(target).toHaveURL(/\/dashboard$/)
  }
  const viewer=await browser.newContext({viewport:{width:320,height:740},colorScheme:'dark'})
  const viewerPage=await viewer.newPage()
  await placementLogin(viewerPage,'reference-viewer@example.test')
  await viewerPage.goto('/review?type=placement_conflict&search=Reference%201')
  await viewerPage.getByRole('button',{name:'Review current filing'}).click()
  await expect(viewerPage.getByText('Printed source and verified destination')).toBeVisible()
  await viewerPage.getByRole('button',{name:'View decision'}).click()
  await expect(viewerPage.getByText('Read-only access. An authorised team member can record a decision.')).toBeVisible()
  await expect(viewerPage.getByRole('button',{name:'Review filing decision'})).toHaveCount(0)
  await noOverflow(viewerPage)
  await viewer.close()
  await page.setViewportSize({width:320,height:740})
  await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'})
  await placementLogin(page,'reference-owner@example.test')
  await page.goto('/review?type=placement_conflict&search=Reference%201')
  await page.getByRole('button',{name:'Review current filing'}).click()
  await expect(page.getByText('Currently filed in Reference A')).toBeVisible()
  const exact=page.getByRole('link',{name:'Open exact source · Page 1'})
  await expect(exact).toHaveAttribute('href',/\/documents\/152e0000.*version=15200000.*page=1/)
  await noOverflow(page)
  await page.getByRole('tab',{name:'Evidence'}).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab',{name:'Decision'})).toBeFocused()
  await page.getByRole('radio',{name:/Keep current filing/}).check()
  await page.getByRole('button',{name:'Review filing decision'}).click()
  await expect(page.getByRole('dialog')).toContainText('Keep this document in its current Matter?')
  await page.getByLabel('Reason',{exact:true}).fill('The source references a separate order but this filing remains its own chain.')
  await page.getByRole('button',{name:'Keep current filing'}).click()
  await expect(page.getByText('This Review item is closed.')).toBeVisible()
  await expect(page.getByRole('heading',{name:'Current filing kept'})).toBeVisible()
  await expect(page.getByText('Reason: The source references a separate order but this filing remains its own chain.')).toBeVisible()
  await page.getByRole('tab',{name:'Evidence'}).click()
  await expect(page.getByText(/Recorded Keep: Reference A \(REF-152-A\) was retained\. Current filing: Reference A \(REF-152-A\)/)).toBeVisible()
  await noOverflow(page)
  await page.setViewportSize({width:1440,height:900})
  await page.goto('/review?type=placement_conflict&search=Reference%202')
  await page.getByRole('button',{name:'Review current filing'}).click()
  await page.getByRole('button',{name:'View decision'}).click()
  await page.getByRole('radio',{name:/Move to Reference B/}).check()
  await expect(page.getByText(/Current impact: Reference 2/)).toBeVisible()
  await expect(page.getByText('No current blockers. A changed dependency invalidates this preview.')).toBeVisible()
  await page.getByRole('button',{name:'Review filing decision'}).click()
  await expect(page.getByRole('dialog')).toContainText('same document, version and PDF source remain available')
  await page.getByLabel('Reason',{exact:true}).fill('Checked source identity, verified target key and all current dependent context.')
  await page.getByRole('button',{name:'Move document'}).click()
  await expect(page.getByText('This Review item is closed.')).toBeVisible()
  await expect(page.getByRole('heading',{name:'Document moved'})).toBeVisible()
  await expect(page.getByText('Reason: Checked source identity, verified target key and all current dependent context.')).toBeVisible()
  await page.getByRole('tab',{name:'Evidence'}).click()
  await expect(page.getByText(/Recorded Move: Reference A \(REF-152-A\) → Reference B \(REF-152-B\)\. Current filing: Reference B \(REF-152-B\)/)).toBeVisible()
  await page.getByRole('link',{name:'Open exact source · Page 1'}).click()
  await expect(page).toHaveURL(/\/documents\/152e0000-0000-0000-0000-000000000002\?.*version=15200000-0000-0000-0000-000000000002.*page=1/)
  await expect(page.getByText('PDF source · Version 1 · Page 1 of 1')).toBeVisible()
  await expect(page.getByRole('link',{name:'Back to Matter'})).toHaveAttribute('href','/matters/152d0000-0000-0000-0000-000000000002')
  await noOverflow(page)
})
test('exact legal date remains provisional until a cited human Review correction, then enters Matter agenda',async({page,browser})=>{
  const viewer=await browser.newContext({viewport:{width:320,height:740},colorScheme:'dark'})
  const viewerPage=await viewer.newPage()
  await login(viewerPage,4)
  await viewerPage.goto('/review?type=deadline_verification')
  await viewerPage.getByRole('button',{name:'Review proposed legal date'}).click()
  await expect(viewerPage.getByText('Source-stated date · Page 2')).toBeVisible()
  await viewerPage.getByRole('button',{name:'View decision'}).click()
  await expect(viewerPage.getByText('Read-only access. An authorised team member can record a decision.')).toBeVisible()
  await expect(viewerPage.getByRole('button',{name:'Review date decision'})).toHaveCount(0)
  await noOverflow(viewerPage)
  await viewer.close()
  await page.setViewportSize({width:320,height:740})
  await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'})
  await login(page)
  await page.goto('/review?type=deadline_verification')
  await page.getByRole('button',{name:'Review proposed legal date'}).click()
  await expect(page.getByRole('link',{name:'Open exact source · Page 2'})).toHaveAttribute('href',
    /\/documents\/153e0000.*version=15300000.*page=2/)
  await noOverflow(page)
  await page.getByRole('tab',{name:'Evidence'}).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab',{name:'Decision'})).toBeFocused()
  await page.getByRole('radio',{name:'Correct date'}).check()
  await page.getByLabel('Human-corrected legal date').fill('2026-10-17')
  await page.getByRole('button',{name:'Review date decision'}).click()
  await expect(page.getByRole('dialog')).toContainText('Correct to 2026-10-17')
  await page.getByLabel('Reason',{exact:true}).fill('The cited page and a written correction establish this date')
  await page.getByRole('button',{name:'Record date decision'}).click()
  await expect(page.getByText('This Review item is closed.')).toBeVisible()
  await page.goto('/matters/153d0000-0000-0000-0000-000000000001?section=deadlines')
  await expect(page.getByText('Legal date agenda')).toBeVisible()
  const verifiedMobileDate=page.getByRole('button',{name:/Reply must be filed by/})
  await expect(verifiedMobileDate).toContainText('Extracted · Verified')
  await verifiedMobileDate.click()
  await expect(page.getByRole('link',{name:'Open exact source · Page 2'})).toHaveAttribute('href',
    /\/documents\/153e0000.*version=15300000.*page=2/)
  await expect(page.getByRole('button',{name:'Correct deadline'})).toBeVisible()
  await noOverflow(page)
  await page.setViewportSize({width:1440,height:900})
  await page.reload()
  await expect(page.getByRole('table',{name:'Legal dates with explicit origin and verification'})).toContainText('17 Oct 2026')
  await noOverflow(page)
})
test('trusted ambiguous global Intake places once and opens the exact new Workbench version', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await login(page)
  await page.goto('/review?type=ambiguous_placement&search=ambiguous-browser-source')
  await page.getByRole('button', { name: /^Choose a Matter destination/ }).click()
  await expect(page.getByText('Exact referenced document · Page 2', { exact: true })).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Open exact Intake source · Page 1', exact: true }).click()
  const download = await downloadPromise
  const downloadPath = await download.path()
  expect(downloadPath).not.toBeNull()
  const sourceBytes = readFileSync(downloadPath!)
  expect(sourceBytes.subarray(0, 5).toString()).toBe('%PDF-')
  expect(sourceBytes.length).toBe(4551)
  expect(createHash('sha256').update(sourceBytes).digest('hex')).toBe('5d02d605e459d75c07055734a17b172b7fa523b6450047e62edbd2c8f5033b88')
  await page.getByRole('button', { name: 'View decision', exact: true }).click()
  await page.getByRole('radio', { name: /Place in Appeal proceeding/ }).check()
  await page.getByRole('button', { name: 'Review destination', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Appeal proceeding')
  await page.getByLabel('Reason', { exact: true }).fill('The exact referenced document identifies the appeal proceeding.')
  await page.getByRole('button', { name: 'Place in selected Matter', exact: true }).click()
  await expect(page).toHaveURL(/\/documents\/[0-9a-f-]+\?version=[0-9a-f-]+&page=1/)
  await expect(page.getByText('PDF source · Version 1 · Page 1 of 4')).toBeVisible()
  await expect(page.getByRole('link', { name: 'Back to Matter' })).toHaveAttribute('href', '/matters/164d0000-0000-0000-0000-000000000002')
  await noOverflow(page)
  await page.setViewportSize({ width: 320, height: 740 })
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' })
  await page.evaluate(() => { document.documentElement.classList.add('dark'); localStorage.setItem('theme', 'dark') })
  await page.goto('/review?status=closed&type=ambiguous_placement&search=ambiguous-browser-source')
  await page.getByRole('button', { name: /^Choose a Matter destination/ }).click()
  await page.getByRole('button', { name: 'View decision', exact: true }).click()
  await expect(page.getByText('Placement recorded', { exact: true })).toBeVisible()
  await expect(page.getByText('Destination: Appeal proceeding', { exact: true })).toBeVisible()
  await expect(page.getByText('This Review item is closed.', { exact: true })).toBeVisible()
  await noOverflow(page)
  await page.goto('/review?status=closed&type=ambiguous_placement&search=unavailable-browser-source')
  await page.getByRole('button', { name: /^Choose a Matter destination/ }).click()
  await expect(page.getByText('The Intake source or an eligible destination changed and is no longer available for this decision.', { exact: false })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Place in selected Matter', exact: true })).toHaveCount(0)
  await noOverflow(page)
})
test('live Review shows exact source evidence, URL selection, confirmation and Viewer authority', async ({ page }) => {
  const hydrationErrors: string[] = []
  page.on('console', message => { if (/hydration|server rendered HTML|did not match/i.test(message.text())) hydrationErrors.push(message.text()) })
  await page.setViewportSize({ width: 1440, height: 900 })
  await login(page)
  await page.goto('/review')
  await page.getByLabel('Search Review').fill('Review source 1')
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await page.getByRole('button', { name: /^Review type/ }).first().click()
  await expect(page).toHaveURL(/item=/)
  expect(new URL(page.url()).searchParams.get('search')).toBe('Review source 1')
  await expect(page.getByRole('status', { name: '' }).filter({ hasText: /^1 item$/ })).toBeVisible()
  const itemUrl = page.url()
  const source = page.getByRole('link', { name: 'Open exact source · Page 2' })
  await expect(source).toHaveAttribute('href', /\/documents\/153e.*version=15300000.*page=2/)
  await source.click()
  await expect(page).toHaveURL(/\/documents\/153e0000-0000-0000-0000-000000000001\?.*version=15300000-0000-0000-0000-000000000001.*page=2/)
  await expect(page.getByText('PDF source · Version 1 · Page 2 of 4')).toBeVisible()
  await expect(page.getByLabel('Current PDF page')).toHaveValue('2')
  await expect(page.locator('[data-pdf-page="2"] canvas')).toBeVisible()
  await page.goto(itemUrl)
  await expect(page.getByRole('tab', { name: 'Evidence', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('tab', { name: 'Evidence', exact: true }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab', { name: 'Decision', exact: true })).toBeFocused()
  await expect(page.getByRole('tabpanel', { name: 'Decision', exact: true })).toBeVisible()
  await expect(page.getByRole('tab', { name: 'Decision', exact: true })).toHaveAttribute('aria-selected', 'true')
  await noOverflow(page)
  await page.getByRole('radio').first().check()
  await page.getByRole('button', { name: 'Review decision', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Confirm selected value' })).toBeDisabled()
  await page.getByLabel('Reason', { exact: true }).fill('Confirmed against the exact cited source page.')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.screenshot({ path: '/tmp/review-desktop.png', animations: 'disabled' })
  await page.context().clearCookies()
  await login(page, 4)
  const viewerUrl = new URL(itemUrl)
  viewerUrl.searchParams.set('tab', 'decision')
  await page.goto(viewerUrl.toString())
  await expect(page.getByText('Read-only access.', { exact: false })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Review decision', exact: true })).toHaveCount(0)
  expect(hydrationErrors).toEqual([])
})
test('responsive processing recovery records manual metadata and keeps the exact PDF available', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 780 })
  await login(page)
  await page.goto('/review?type=processing_recovery&search=Review+source+5')
  await page.getByRole('button', { name: 'Continue document manually', exact: true }).click()
  await expect(page.getByText('Model output invalid', { exact: false })).toBeVisible()
  const source = page.getByRole('link', { name: 'Open exact source · Page 1' })
  await expect(source).toHaveAttribute('href', /\/documents\/153e.*version=15300000.*page=1/)
  await noOverflow(page)
  await page.getByRole('button', { name: 'View decision', exact: true }).click()
  await page.getByLabel('Document type').selectOption('SCN')
  await page.getByLabel('Reference number').fill('SCN/MANUAL/42')
  await page.getByLabel('Document date').fill('2026-09-15')
  await page.getByLabel('Direction').selectOption('incoming')
  await page.getByLabel('Issued by').fill('GST Authority')
  await page.getByRole('button', { name: 'Review manual continuation', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Automated extraction will not be retried.')
  await page.getByLabel('Reason', { exact: true }).fill('Verified the core details against the immutable PDF.')
  await page.getByRole('button', { name: 'Continue manually', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.getByText('Manual continuation recorded', { exact: true })).toBeVisible()
  await expect(page.getByText('This Review item is closed.', { exact: true })).toBeVisible()
  await noOverflow(page)
  await page.getByRole('tab', { name: 'Evidence', exact: true }).click()
  const exactSource = page.getByRole('link', { name: 'Open exact source · Page 1' })
  await expect(exactSource).toHaveAttribute('href', /\/documents\/153e.*version=15300000.*page=1/)
  await exactSource.click()
  await expect(page).toHaveURL(/\/documents\/153e0000-0000-0000-0000-000000000005\?.*version=15300000-0000-0000-0000-000000000005.*page=1/)
  await expect(page.getByRole('banner').getByText('SCN/MANUAL/42', { exact: true })).toBeVisible()
  await expect(page.getByText('PDF source · Version 1 · Page 1 of 2')).toBeVisible()
  await noOverflow(page)
})
test('200% browser zoom preserves selection and a live supported-value decision closes Review', async () => {
  const zoom = await launchChromiumPageZoom('http://127.0.0.1:3103', { width: 1440, height: 1000 })
  try {
    const page = zoom.page
    await login(page)
    await page.goto('/review?search=Review+source+1')
    await zoom.setZoom(2)
    await page.getByRole('button', { name: /^Review type/ }).click()
    await page.getByRole('button', { name: 'View decision', exact: true }).click()
    await page.getByRole('radio').first().check()
    await page.getByRole('button', { name: 'Review decision', exact: true }).click()
    await page.getByLabel('Reason', { exact: true }).fill(reason500)
    await expect(page.getByLabel('Reason', { exact: true })).toHaveValue(reason500)
    expect(await page.getByLabel('Reason', { exact: true }).evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
    await noOverflow(page)
    await page.screenshot({ path: '/tmp/review-zoom-confirmation.png', animations: 'disabled' })
    await page.getByRole('button', { name: 'Confirm selected value' }).click()
    await expect(page.getByRole('dialog')).not.toBeVisible()
    await expect(page.getByText('This Review item is closed.', { exact: true })).toBeVisible()
    await expect(page.getByText('Recorded outcome', { exact: true })).toBeVisible()
    await noOverflow(page)
  } finally { await zoom.close() }
})
test('320px dark reduced-motion list/detail retains filters, evidence and clarification', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 740 })
  await page.emulateMedia({ reducedMotion: 'reduce', colorScheme: 'dark' })
  await login(page, 3)
  await page.evaluate(() => { document.documentElement.classList.add('dark'); localStorage.setItem('theme', 'dark') })
  await page.goto('/review')
  const origin = page.getByRole('button', { name: 'Review type', exact: true }).last()
  await origin.scrollIntoViewIfNeeded()
  await origin.focus()
  const scroller = page.locator('[data-review-list-scroller]')
  const scrollBefore = await scroller.evaluate(element => element.scrollTop)
  expect(scrollBefore).toBeGreaterThan(0)
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Review type', exact: true })).toBeFocused()
  await page.getByRole('button', { name: 'Back to list' }).focus()
  await page.keyboard.press('Enter')
  await expect(origin).toBeFocused()
  await expect.poll(() => scroller.evaluate(element => element.scrollTop)).toBe(scrollBefore)
  await page.getByLabel('Search Review').fill('Review source 6')
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await page.getByRole('button', { name: 'Review tax period', exact: true }).click()
  await expect(page.getByText('Derived comparison: 2019-20')).toBeVisible()
  expect(await page.locator('aside blockquote').evaluate(element => element.textContent!.length > 400 && element.scrollWidth <= element.clientWidth)).toBe(true)
  expect(await page.locator('aside header p').first().evaluate(element => element.textContent!.length > 200 && element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: '/tmp/review-mobile-long-evidence.png', animations: 'disabled' })
  await noOverflow(page)
  await page.getByRole('button', { name: 'View decision', exact: true }).click()
  await expect(page.getByRole('radio')).toHaveCount(1)
  await page.getByRole('radio').check()
  await page.getByRole('button', { name: 'Review decision', exact: true }).click()
  await page.getByLabel('Reason', { exact: true }).fill(reason500)
  expect(await page.getByLabel('Reason', { exact: true }).evaluate(element => element.scrollWidth <= element.clientWidth && element.clientHeight >= 80)).toBe(true)
  await expect(page.getByRole('dialog').getByRole('button', { name: 'Request clarification', exact: true })).toBeInViewport()
  await page.screenshot({ path: '/tmp/review-mobile-long-reason.png', animations: 'disabled' })
  await noOverflow(page)
  await page.getByRole('dialog').getByRole('button', { name: 'Request clarification', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.getByText('Clarification requested', { exact: true })).toBeVisible()
  await page.screenshot({ path: '/tmp/review-mobile-dark.png', animations: 'disabled' })
  await page.getByRole('button', { name: 'Back to list' }).click()
  await expect(page.getByLabel('Search Review')).toHaveValue('Review source 6')
  await noOverflow(page)
})

test('empty filtering, real route loading and error retry preserve an operable workspace', async ({ page }) => {
  await login(page)
  await page.goto('/review?search=No-synthetic-document-matches')
  await expect(page.getByRole('heading', { name: 'No Review items found' })).toBeVisible()
  await expect(page.getByRole('status').filter({ hasText: /^0 items$/ })).toBeVisible()
  await noOverflow(page)
  assertDisposable()
  const lock = spawn('docker', dbArgs)
  let output = ''
  lock.stdout.on('data', bytes => { output += bytes })
  lock.stdin.write("BEGIN; SET LOCAL statement_timeout='20s'; LOCK TABLE public.review_items IN ACCESS EXCLUSIVE MODE; SELECT 'ready';\n")
  try {
    await expect.poll(() => output).toContain('ready')
    await page.goto('/review?search=Review+source+6', { waitUntil: 'commit' })
    await expect(page.getByRole('status').filter({ hasText: /Loading Review/ })).toBeVisible()
    await page.screenshot({ path: '/tmp/review-loading.png', animations: 'disabled' })
  } finally {
    lock.stdin.end('ROLLBACK;\n')
    await new Promise<void>(resolve => lock.on('exit', () => resolve()))
  }
  await expect(page.getByLabel('Search Review')).toHaveValue('Review source 6')
  const signature = 'public.read_review_queue(text,text,text,text,integer,integer)'
  try {
    db(`REVOKE EXECUTE ON FUNCTION ${signature} FROM authenticated;`)
    await page.goto('/review?search=Fault-probe')
    await expect(page.getByRole('alert').filter({ hasText: 'Review could not be loaded.' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Retry Review' })).toBeVisible()
    await page.screenshot({ path: '/tmp/review-error.png', animations: 'disabled' })
  } finally { db(`GRANT EXECUTE ON FUNCTION ${signature} TO authenticated;`) }
  await page.getByRole('button', { name: 'Retry Review' }).click()
  await expect(page.getByLabel('Search Review')).toHaveValue('Fault-probe')
  await expect(page.getByRole('heading', { name: 'No Review items found' })).toBeVisible()
  await noOverflow(page)
})
